export const Home = [
    { imageLink: '../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: '../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../../../assets/images/gun.jpeg', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
];

export const NewReleases  = [
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },


];

export const Top_Charts  = [
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/images/whatspp.png', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

];