export const Home = [
    { imageLink: '../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: '../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
    { imageLink: ' ../assets/images/img1.png', gameName: 'CrossFire: Legends', provider: 'Tencent Games' },
];

export const NewReleases  = [
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },
    { imageLink: ' ../../../assets/new.jpg', gameName: 'Robin Hood Legends ', provider: 'Big Fish Games' },


];

export const Top_Charts  = [
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },
    { imageLink: ' ../../../assets/top.jpg', gameName: 'Dr. Driving 2', provider: 'SUD Inc' },

];